name: whats_app_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  page_transition: ^2.1.0
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  country_picker: ^2.0.23
  country_codes: ^2.2.0
  country_dial_code: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/image1.jpg
    - assets/flags/